name: CI Deployment to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 3.107.83.246
          username: ubuntu
          key: ${{ secrets.SERVER2_PRIVATE_KEY }}
          passphrase: password # If your private key has a passphrase, otherwise leave it out
          port: 22
          script: |
            cd /var/www/superiorapp/
            git pull origin main
            php artisan cache:clear
            php artisan migrate --force
            npm install
            npm run build
            echo "Deployment complete."
